### ISSUE TITLE
点了“预览”按钮不出预览效果

### ISSUE THREAD

**Issue by Dreamer57** [LEOYoon-Tsaw/Squirrel-Designer#2]
点击“预览”按钮后，按钮变成“收预览”，但是没有出现预览界面，把app删了重添加也是如此。

第一次打开的时候好好的，但是我复制了一段皮肤代码，点击了“代码变预览”，然后就再也不能用“预览”按钮了。

**Comment by LEOYoon-Tsaw** [comment]
代碼有問題唄

**Comment by Dreamer57** [comment]
那段代码我从鼠须管里拷出来的，可能是有些问题。

我之后后悔了，又点了“复原”按钮，复原后又还是不能预览。

然后我又把app删除了，重新安装还是重新拖进来的，反正算是重装了，然后还是不能预览。

但我都把app重装了呀，难道是往电脑其它地方写文件啦？没删干净？

那我该怎样才能再正常使用这个app？

**Comment by LEOYoon-Tsaw** [comment]
它的文件在sandbox裡，位於`~/Library/Containers/Squirrel Designer`
刪除內容即可恢復

**Comment by Dreamer57** [comment]
感谢大佬，正常了～
