### ISSUE TITLE
字体大小用浮点数会报错，请求改为整数

### ISSUE THREAD

**Issue by OscarXWei** [LEOYoon-Tsaw/Squirrel-Designer#3]
现在的程序的字体大小都是用带小数点的浮点数，鼠须管无法正确显示字体大小，所有的皮肤都是默认的字号（似乎是24号字），把程序里面的浮点数值改为整数则会正常（不过alpha值要用浮点数）

**Comment by LEOYoon-Tsaw** [comment]
沒遇到這樣的問題

**Comment by LEOYoon-Tsaw** [comment]
嗯，這個好做

**Comment by LEOYoon-Tsaw** [comment]
Reverted，已在[鼠鬚管](https://github.com/rime/squirrel/commit/f4dc96d08ffa1f483d1663ac0788564672033293)修改，將接受浮點數字號
