### ISSUE TITLE
[Feature Request] 添加对 hilited_comment_text_color 预览支持 

### ISSUE THREAD

**Issue by pdog18** [LEOYoon-Tsaw/Squirrel-Designer#6]
`hilited_comment_text_color` 未体现在候选词面板上。

**Comment by LEOYoon-Tsaw** [comment]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/4469383/233788731-98560496-4149-4f8f-bd0c-6026b60650d1.png">
好像沒有問題吧

**Comment by pdog18** [comment]
> 
这里的 「疑依模去」不是应该是 `Comment Text Color` ? 
而 `hilited_comment_text_color` 不是当前选中的候选词(通常是第一个)的注释文字吗?

**Comment by LEOYoon-Tsaw** [comment]
這個是選中項了，外面有個框不是

**Comment by pdog18** [comment]
Squirrel Designer
Version 1.11 (27)

1.11(27) 不是最新版吗?
---
<img width="959" alt="image" src="https://user-images.githubusercontent.com/17060376/233789697-9eba93a2-29bd-47fb-a9de-cec6ed3c6d76.png">

**Comment by LEOYoon-Tsaw** [comment]
因爲你這儿的選中項沒有comment呀

**Comment by pdog18** [comment]
> 因爲你這儿的選中項沒有comment呀

我先确定一件事: 这里的选中项是哪个，我们可以进行调整吗? 或者候选词的内容，我们可以自由设定吗?
因为我安装好 Squirrel-Designer 后，选中项总是第一个，并且选中项总是没有 comment，所以始终无法看到 `hilited_comment_text_color` 效果(所以需要 `hilited_comment_text_color` 的预览支持)。

**Comment by LEOYoon-Tsaw** [comment]
> 这里的选中项是哪个，我们可以进行调整吗? 

可以，`cmd`+`,`

**Comment by pdog18** [comment]
如果可以的话, 建议增加「可以通过 Preferences 修改候选项」,或者打开  app  时, 默认的当前选中的候选词是携带  comment  的

**Comment by LEOYoon-Tsaw** [comment]
新版可以用鼠標選字了，會更方便更改選中項

> 增加「可以通过 Preferences 修改候选项」,或者打开 app 时, 默认的当前选中的候选词是携带 comment 的

就不再做了

**Comment by pdog18** [comment]
> 新版可以用鼠標選字了，會更方便更改選中項
> 
> > 增加「可以通过 Preferences 修改候选项」,或者打开 app 时, 默认的当前选中的候选词是携带 comment 的
> 
> 就不再做了

建议还是在主窗口上添加打开 Preferences 的快捷键，示意可以「自定义候选词、label、及 comment」，这会极大的提高 Designer 的使用便利。

**Comment by LEOYoon-Tsaw** [comment]
沒有哪個macOS的App在主界面上有打開設置的按鈕，都是統一的cmd+，或者從菜單欄打開
