### ISSUE TITLE
[Bug]某个字体值未设置时，Crash

### ISSUE THREAD

**Issue by pdog18** [LEOYoon-Tsaw/Squirrel-Designer#7]
![iShot_2023-04-22_22 11 02](https://user-images.githubusercontent.com/17060376/233789929-f3c72f16-ef84-45e6-97c9-c6c70ffe378f.gif)

**Comment by LEOYoon-Tsaw** [comment]
Ok, 是個bug

**Comment by LEOYoon-Tsaw** [comment]
Solved by [76ae0fe](https://github.com/LEOYoon-Tsaw/Squirrel-Designer/commit/76ae0fe5c094bee64599c7272f5d09493085fdfb)
